# Changes here will be overwritten by Copier
_commit: 53383b0
_src_path: git@github.com:atropos112/template-python-pkg.git
author: atropos
email: sv7n@pm.me
project_description: Package containing generic/reusable content one can reuse in
    many projects.
project_name: atro-core
