---
name: Test And Publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  test:
    uses: atropos112/atropylib/.github/workflows/devenv_test.yaml@main
    if: github.repository != 'atropos112/template-python-pkg'
    secrets: inherit
  publish:
    runs-on: ubuntu-latest
    needs: test
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        shell: devenv shell bash -- -e {0}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('uv.lock') }}
      - name: Install devenv.sh
        shell: bash
        run: nix profile install nixpkgs#devenv
      - name: Run pre-commit hooks and tests
        run: devenv test
      - name: Set PyProject Version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version $VERSION
      - name: Build 
        run: uv build  
      - name: Publish
        run: uv publish 
      - name: Commit updated pyproject.toml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pyproject.toml
          git commit -m "Update pyproject.toml version to $VERSION"
      - name: Push changes
        run: |
          git config pull.rebase true
          git pull origin main
          git push origin HEAD:main

